brace_style = "AlwaysNextLine"
fn_single_line = true
format_strings = true
tab_spaces = 2
wrap_comments = true
format_code_in_doc_comments = true
match_arm_blocks = false
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
reorder_impl_items = true
imports_granularity = "Crate"
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20
fn_call_width = 80
use_field_init_shorthand = true